# Generated by Django 3.2.4 on 2021-06-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seuser',
            name='username',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
