# Generated by Django 3.2.4 on 2021-06-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seuser', '0003_alter_seuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seuser',
            options={'verbose_name': '링킹 스페이스 사용자', 'verbose_name_plural': '링킹 스페이스 사용자'},
        ),
    ]
