# Generated by Django 3.2.4 on 2021-06-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seuser', '0004_alter_seuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='seuser',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='.사용자이메일'),
            preserve_default=False,
        ),
    ]
