# Generated by Django 3.2.4 on 2021-06-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seuser', '0005_seuser_useremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seuser',
            name='useremail',
        ),
        migrations.RemoveField(
            model_name='seuser',
            name='username',
        ),
        migrations.AddField(
            model_name='seuser',
            name='user_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='seuser',
            name='user_age',
            field=models.IntegerField(default=-1, verbose_name='나이'),
        ),
        migrations.AddField(
            model_name='seuser',
            name='user_email',
            field=models.EmailField(default='email@none.com', max_length=128, verbose_name='.사용자이메일'),
        ),
        migrations.AddField(
            model_name='seuser',
            name='user_id',
            field=models.CharField(default='anonymous', max_length=64, verbose_name='사용자명'),
        ),
        migrations.AddField(
            model_name='seuser',
            name='user_interest',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='사용자 관심사'),
        ),
        migrations.AddField(
            model_name='seuser',
            name='user_name',
            field=models.CharField(default='nouser', max_length=200),
        ),
        migrations.AddField(
            model_name='seuser',
            name='user_sex',
            field=models.CharField(default='남자', max_length=200, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='seuser',
            name='password',
            field=models.CharField(default='0', max_length=64, verbose_name='비밀번호'),
        ),
    ]
