# Generated by Django 3.2.4 on 2021-06-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seuser', '0006_auto_20210619_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seuser',
            name='user_name',
            field=models.CharField(default='nouser', max_length=200, verbose_name='사용자 아이디'),
        ),
    ]
