# Generated by Django 3.2.4 on 2021-06-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seuser', '0007_alter_seuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seuser',
            name='user_name',
            field=models.CharField(default='nouser', max_length=200),
        ),
    ]
