# Generated by Django 3.2.4 on 2021-06-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seuser', '0009_alter_seuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seuser',
            name='user_email',
            field=models.EmailField(default='email@none.com', max_length=128, verbose_name='사용자이메일'),
        ),
    ]
