# Generated by Django 3.2.4 on 2021-06-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seuser', '0010_alter_seuser_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seuser',
            name='user_id',
            field=models.CharField(default='nouser', max_length=200, verbose_name='사용자 아이디'),
        ),
        migrations.AlterField(
            model_name='seuser',
            name='user_name',
            field=models.CharField(default='anonymous', max_length=64, verbose_name='사용자명'),
        ),
    ]
