# Generated by Django 3.2.3 on 2021-05-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=200, unique=True)),
                ('user_name', models.CharField(max_length=200)),
                ('user_sex', models.CharField(blank=True, max_length=200, null=True)),
                ('user_age', models.IntegerField(blank=True, null=True)),
                ('user_address', models.CharField(blank=True, max_length=200, null=True)),
                ('user_interest', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
