# Generated by Django 3.2.3 on 2021-05-23 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_address', models.CharField(max_length=1000)),
                ('place_category', models.CharField(max_length=200)),
                ('place_contact', models.CharField(max_length=200)),
                ('place_name', models.CharField(max_length=200)),
                ('place_options', models.CharField(max_length=1000)),
                ('place_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_written_time', models.DateTimeField(auto_now=True)),
                ('review_text', models.CharField(max_length=1000)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_time', models.CharField(max_length=200)),
                ('payment_info', models.CharField(max_length=1000)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
